### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by drazisil** [drazisil/circleci-testing#3]
I'm a test

**Comment by drazisil** [comment]
What is a test?

**Comment by drazisil** [comment]
A test by any other name...

**Comment by drazisil** [comment]
would still be a test

**Comment by drazisil** [comment]
But...

**Comment by drazisil** [comment]
What if it's not a test?

**Comment by drazisil** [comment]
What if it's something else?

**Comment by drazisil** [comment]
What is it's a message?

**Comment by drazisil** [comment]
two test

**Comment by drazisil** [comment]
foo

**Comment by drazisil** [comment]
goal?

**Comment by drazisil** [comment]
moo

**Comment by drazisil** [comment]
Mumbles

**Comment by drazisil** [comment]
peanuts

**Comment by drazisil** [comment]
rabbits

**Comment by drazisil** [comment]
grr

**Comment by drazisil** [comment]
Huh?

**Comment by drazisil** [comment]
And now?

**Comment by drazisil** [comment]
So maybe....

**Comment by drazisil** [comment]
A test for me...

**Comment by drazisil** [comment]
Another test for me

**Comment by drazisil** [comment]
@JustinC474 Will this work?

**Comment by drazisil** [comment]
So, me.

**Comment by drazisil** [comment]
I hate typos

**Comment by drazisil** [comment]
I just want to talk...

**Comment by drazisil** [comment]
What about a channel mention?

**Comment by drazisil** [comment]
Channel mention, WITH save?

**Comment by drazisil** [comment]
Meh, maybe @JustinC474  can live without linked channels. I'm sure it's a minor thing. ;)

**Comment by drazisil** [comment]
Ahem, @JustinC474 needs to actually have a userid, bots don't like talking to teams

**Comment by drazisil** [comment]
And I need to restart the bot when it crashed, don't I, @JustinC474 ?

**Comment by drazisil** [comment]
So, we need a good setup system, but do links work now?

**Comment by drazisil** [comment]
Would you like to buy a vowel?

**Comment by drazisil** [comment]
Thanks for the help testing @JustinC474 :)

**Comment by JustinC474** [comment]
herp derp doo
